### ISSUE TITLE
Run Onboard Camera on Jetson

### ISSUE THREAD

**Issue by gustavz** [AlexanderRobles21/YOLO-darknet-on-Jetson-TX2#1]
Hey Alex,

thanks for your great github.

But unfortuantely the command for running the onboard camera on the jetson tx2 does not longer work.

Could you update it?

Would be awesome, thanks!

Gustav

**Comment by gustavz** [comment]
Nevermind. it was due to my GSTREAM unable opencv build.
Fixed it!

**Comment by Alro10** [comment]
Hi GustavZ!

You can install OpenCV from this repository.... https://github.com/jetsonhacks/buildOpenCVTX2
