### ISSUE TITLE
jetson in built cam with darknet

### ISSUE THREAD

**Issue by CharithEkanayake** [AlexanderRobles21/YOLO-darknet-on-Jetson-TX2#2]
./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)I420, framerate=(fraction)30/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink"

is throwing the following error
Couldn't connect to webcam.
: No such file or directory
darknet: ./src/utils.c:256: error: Assertion `0' failed.

**Comment by Alro10** [comment]
Hi! @charithforex if you use usb webcam, try to replace: "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)I420, framerate=(fraction)30/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink"  for /dev/video1

**Comment by BourbonCreams** [comment]
I get the same error when trying to use the onboard camera by running your command.

**Comment by Alro10** [comment]
Hi @BourbonCreams !
I found an issue when sed and sudo with string replace and update my repository! Also there is a new version of YOLO called yolov3. Please check the last part of readme.

$ sudo sed -i 's/GPU=0/GPU=1/g' Makefile

$ sudo sed -i 's/CUDNN=0/CUDNN=1/g' Makefile

$ sudo sed -i 's/OPENCV=0/OPENCV=1/g' Makefile

Can you tell me your Jetson configuration?

**Comment by BourbonCreams** [comment]
I reinstalled OpenCV with `-D WITH_GSTREAMER=ON -D WITH_FFMPEG=ON ` and it eventually worked. For your information I'm on Ubuntu 16.04, OpenCV 3.4 and CUDA 9.0.
