### ISSUE TITLE
overclock

### ISSUE THREAD

**Issue by alemelis** [AlexanderRobles21/YOLO-darknet-on-Jetson-TX2#5]
Hi there!

thanks for the nice walkthrough.
I found that you can even speed up yolo by overclocking the Jetson.
See [this forum thread](https://devtalk.nvidia.com/default/topic/1011317/jetson-tx2/how-to-boost-the-power-of-tx2-to-15w-/) for reference.

**Comment by Alro10** [comment]
Hi @alemelis  Thanks for the information. I will update this repository as soon as possible.
